import { useState, type FormEvent } from 'react';
import { useMutation } from '@tanstack/react-query';
import { Link } from 'react-router-dom';
import { search } from '../../api/search';
import { PollCard } from '../../components/PollCard';
import { Avatar } from '../../components/Avatar';
import { useSession } from '../../app/session-provider';
type SearchType = 'all' | 'polls' | 'users'; type SearchSort = 'relevance' | 'newest' | 'popular';
export function SearchPage() { const { user } = useSession(); const [query, setQuery] = useState(''); const [type, setType] = useState<SearchType>('all'); const [sort, setSort] = useState<SearchSort>('relevance'); const searchMutation = useMutation({ mutationFn: () => search({ q: query.trim(), type, sort }) }); const submit = (event: FormEvent) => { event.preventDefault(); if (query.trim().length >= 2) searchMutation.mutate(); }; return <main id="main-content"><h1>Search</h1><form onSubmit={submit}><label>Search<input value={query} onChange={(event) => setQuery(event.target.value)} minLength={2} required /></label><label>Result type<select value={type} onChange={(event) => setType(event.target.value as SearchType)}><option value="all">All</option><option value="polls">Polls</option><option value="users">Users</option></select></label><label>Sort<select value={sort} onChange={(event) => setSort(event.target.value as SearchSort)}><option value="relevance">Relevance</option><option value="newest">Newest</option><option value="popular">Popular</option></select></label><button type="submit" disabled={searchMutation.isPending || query.trim().length < 2}>Search</button></form>{searchMutation.isError ? <p role="alert">{searchMutation.error instanceof Error ? searchMutation.error.message : 'Search failed.'}</p> : null}{searchMutation.data?.items.map((item) => item.type === 'poll' ? <PollCard key={`poll-${item.poll.id}`} poll={item.poll} viewerId={user?.id} /> : <article key={`user-${item.user.id}`}><Avatar name={item.user.profile.displayName || item.user.username} src={item.user.profile.avatarUrl} /><Link to={`/users/${item.user.id}`}>{item.user.profile.displayName || item.user.username}</Link><p>@{item.user.username}</p></article>)}</main>; }
