name: yaskapp_mobile
description: Flutter client for Yaskapp.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.4.1
  go_router: ^14.2.0
  http: ^1.2.1
  http_parser: ^4.1.2
  image_picker: ^1.1.2
  web_socket_channel: ^3.0.0
  firebase_core: ^4.14.0
  firebase_messaging: ^16.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/yaskapp_logo.png
    - assets/branding/search_icon.png
    - assets/branding/notification_icon.png
    - assets/branding/like_icon.png
    - assets/branding/dislike_icon.png
    - assets/branding/comments_icon.png
    - assets/branding/create_poll_icon.png
    - assets/branding/home_icon.png
    - assets/branding/subscriptions_icon.png
