import { useEffect, useState, type FormEvent } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { deleteAvatar, updateMyProfile, uploadAvatar } from '../../api/profiles';
import type { AuthUser, PublicProfile } from '../../api/models';
import { useSession } from '../../app/session-provider';
import { Avatar } from '../../components/Avatar';

function changedFields(user: AuthUser, input: { displayName: string; bio: string; countryCode: string }) { const changed: { displayName?: string; bio?: string | null; countryCode?: string } = {}; if (input.displayName !== user.profile.displayName) changed.displayName = input.displayName; if (input.bio !== (user.profile.bio ?? '')) changed.bio = input.bio || null; if (input.countryCode !== (user.profile.countryCode ?? '')) changed.countryCode = input.countryCode; return changed; }
export function MyProfilePage() {
  const { user, updateUser } = useSession(); const queryClient = useQueryClient(); const [displayName, setDisplayName] = useState(''); const [bio, setBio] = useState(''); const [countryCode, setCountryCode] = useState(''); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false);
  useEffect(() => { if (user) { setDisplayName(user.profile.displayName); setBio(user.profile.bio ?? ''); setCountryCode(user.profile.countryCode ?? ''); } }, [user]);
  if (!user) return <main id="main-content"><p role="status">Loading your profile…</p></main>;
  const applyUser = (updated: AuthUser) => { updateUser(updated); queryClient.setQueryData<PublicProfile>(['profile', updated.id], (existing) => existing ? { ...existing, username: updated.username, status: updated.status, profile: updated.profile } : existing); };
  const submit = async (event: FormEvent) => { event.preventDefault(); const input = changedFields(user, { displayName, bio, countryCode }); if (!Object.keys(input).length) return; setPending(true); setError(null); try { applyUser(await updateMyProfile(input)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not save profile.'); } finally { setPending(false); } };
  const changeAvatar = async (file: File | null) => { if (!file) return; setPending(true); setError(null); try { applyUser(await uploadAvatar(file)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not upload avatar.'); } finally { setPending(false); } };
  const removeAvatar = async () => { setPending(true); setError(null); try { applyUser(await deleteAvatar()); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not remove avatar.'); } finally { setPending(false); } };
  return <main id="main-content" className="profile-page"><header className="profile-header"><Avatar name={user.profile.displayName || user.username} src={user.profile.avatarUrl} size={72} /><div><p className="eyebrow">Account</p><h1>My profile</h1><p>@{user.username}</p></div></header><form className="form-panel" aria-label="Edit profile" onSubmit={(event) => void submit(event)}><label className="field">Avatar<input aria-label="Avatar" type="file" accept="image/jpeg,image/png,image/webp" disabled={pending} onChange={(event) => void changeAvatar(event.currentTarget.files?.[0] ?? null)} /></label>{user.profile.avatarUrl ? <button className="button" type="button" disabled={pending} onClick={() => void removeAvatar()}>Remove avatar</button> : null}<label className="field">Display name<input value={displayName} onChange={(event) => setDisplayName(event.target.value)} disabled={pending} /></label><label className="field">Bio<textarea value={bio} onChange={(event) => setBio(event.target.value)} disabled={pending} /></label><label className="field">Country code<select value={countryCode} onChange={(event) => setCountryCode(event.target.value)} disabled={pending}><option value="">Not specified</option><option value="BY">BY</option><option value="PL">PL</option></select></label>{error ? <p className="inline-alert" role="alert">{error}</p> : null}<div className="form-actions"><button className="button button--primary" type="submit" disabled={pending}>Save profile</button></div></form></main>;
}
